name = "form-handler"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
NOTIFICATION_EMAIL = "triphosphatelp@gmail.com"

# Enable logging
[observability.logs]
enabled = true

# Routes
[[routes]]
pattern = "tripmixes.com/submit-form*"
zone_id = "745313294601ce924f0e49745603a937"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "formsubmissions"
database_id = "a8283608-a362-410a-80d8-76bddfa1df8c"

# Add this section to declare the secret (but not its value)
[secrets]
REDDIT_BEARER_TOKEN