name = "form-handler"
main = "src/worker.js"
compatibility_date = "2024-03-18"

# All variables in one [vars] section
[vars]
NOTIFICATION_EMAIL = "triphosphatelp@gmail.com"
REDDIT_BEARER_TOKEN = ""  # Placeholder for the secret

# Enable logging
[observability.logs]
enabled = true

# Routes
[[routes]]
pattern = "tripmixes.com/submit-form*"
zone_id = "745313294601ce924f0e49745603a937"

[[routes]]
pattern = "tripmixes.com/api/feedback-queue*"
zone_id = "745313294601ce924f0e49745603a937"

# Production D1 Database
[[d1_databases]]
binding = "DB"
database_name = "formsubmissions"
database_id = "a8283608-a362-410a-80d8-76bddfa1df8c"