name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Create config file
        run: |
          echo "export const config = {
            GOOGLE_SHEETS_ENDPOINT: '${{ secrets.GOOGLE_SHEETS_ENDPOINT }}'
          };" > src/config.js
      
      - name: Commit config file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/config.js
          git commit -m "Add config file for deployment" || echo "No changes to commit"
          git push